name: CI/CD for Hello World

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build pytest

    - name: Build the project
      run: python -m build

    - name: Install the package
      run: pip install dist/*.whl

    - name: Run tests
      run: pytest

  deploy:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          key: ${{secrets.EC2_SSH_KEY}}
          known_hosts: ${{ secrets.EC2_HOST}}
  
      - name: Copy files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.216.190.94 "mkdir -p ~/hello_world"
          scp hello.py ubuntu@18.216.190.94:~/hello_world/
  
      - name: Run Hello World script
        run: ssh -o StrictHostKeyChecking=no ubuntu@18.216.190.94 "python3 ~/hello_world/hello.py"
